FROM node:alpine

WORKDIR /app

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

COPY package.json .
RUN npm install -g typescript

COPY . .

RUN npm install
RUN npm run build

CMD [ "npm", "start" ]
